<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FOOTWEAR</name>
   <tag></tag>
   <elementGuidId>d003e34d-35cb-443b-8599-8d7e703c035d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.site-nav__link.site-nav__link--has-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9152fc0-c685-4345-98c8-289364c44bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/footwear</value>
      <webElementGuid>f2cd29c1-8acc-49b3-924b-74dbc90d8a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--has-dropdown</value>
      <webElementGuid>92d7ec0c-34fe-4547-ae27-a5eeaf8bcc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FOOTWEAR </value>
      <webElementGuid>b662c241-8cc6-4f15-a894-4bb4ddc378eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/div[2]/div[@class=&quot;header-wrapper&quot;]/header[@class=&quot;site-header&quot;]/div[@class=&quot;page-width&quot;]/div[@class=&quot;header-layout header-layout--right header-layout--mobile-logo-only&quot;]/div[@class=&quot;header-item header-item--navigation text-right small--hide&quot;]/ul[@class=&quot;site-nav site-navigation small--hide&quot;]/li[@class=&quot;site-nav__item site-nav__expanded-item site-nav--has-dropdown is-focused&quot;]/a[@class=&quot;site-nav__link site-nav__link--has-dropdown&quot;]</value>
      <webElementGuid>2974de23-7106-4e14-b9a3-9eb5c8e2efe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li/a</value>
      <webElementGuid>587777e2-1910-4c62-9822-b7868afd160b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FOOTWEAR')]</value>
      <webElementGuid>dc42e5c2-4236-44b6-93f2-3026dd94e0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[3]</value>
      <webElementGuid>e1ff9bc9-e2b8-467d-8470-64cc48e3ac5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::a[4]</value>
      <webElementGuid>02c68e2a-0ea5-4dec-b316-055c0c41fcc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::a[1]</value>
      <webElementGuid>7e9b2a31-6374-4248-946d-34e40929c38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandals'])[2]/preceding::a[2]</value>
      <webElementGuid>dcaf1e5b-02ca-4488-81d0-f5335ebd8ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FOOTWEAR']/parent::*</value>
      <webElementGuid>3cde1f37-e39d-4f3c-aa32-b6a1b794596f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/footwear')])[2]</value>
      <webElementGuid>cdaf6c30-a201-4907-968a-2e9c55aeb51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>0c84de64-5b99-4bc3-a103-1d9d81911455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/footwear' and (text() = 'FOOTWEAR ' or . = 'FOOTWEAR ')]</value>
      <webElementGuid>3b5857f0-0768-4721-8cfe-bac808d9496e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
