<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NON-FOOTWEAR</name>
   <tag></tag>
   <elementGuidId>58da6e38-66ed-4177-bd31-dc8579bb5a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.site-nav__item.site-nav__expanded-item.site-nav--has-dropdown.is-focused > a.site-nav__link.site-nav__link--has-dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ef80ede-017f-4fe6-a401-d45b1e4a0cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/collections/all-essentials</value>
      <webElementGuid>a00afe8d-0faf-4717-8fb4-5ef95969dafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>site-nav__link site-nav__link--has-dropdown</value>
      <webElementGuid>52919946-6a44-4a9a-b012-475ecbe1ba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NON-FOOTWEAR </value>
      <webElementGuid>88c043f6-f213-4a48-929c-186c90287799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-header&quot;)/div[2]/div[@class=&quot;header-wrapper&quot;]/header[@class=&quot;site-header&quot;]/div[@class=&quot;page-width&quot;]/div[@class=&quot;header-layout header-layout--right header-layout--mobile-logo-only&quot;]/div[@class=&quot;header-item header-item--navigation text-right small--hide&quot;]/ul[@class=&quot;site-nav site-navigation small--hide&quot;]/li[@class=&quot;site-nav__item site-nav__expanded-item site-nav--has-dropdown is-focused&quot;]/a[@class=&quot;site-nav__link site-nav__link--has-dropdown&quot;]</value>
      <webElementGuid>ecb6f30e-06bc-4368-9c26-671cdd39af39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-header']/div[2]/div/header/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>04b91975-c75a-490c-84a0-3a66a2080b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NON-FOOTWEAR')]</value>
      <webElementGuid>3e83b746-5a7f-4d83-9422-e1e2a7b0ae48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size Guide'])[2]/following::a[1]</value>
      <webElementGuid>38f159d7-1276-42f3-9def-b5b5e0e42af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sneakers'])[2]/following::a[2]</value>
      <webElementGuid>5fc2023f-dd87-416c-9bc5-578eb74b6aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[2]/preceding::a[1]</value>
      <webElementGuid>18dd2bd4-23a3-4715-96b4-99e3600de669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pants'])[2]/preceding::a[2]</value>
      <webElementGuid>0f2d53ae-8ef5-425a-b55c-65976229eac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NON-FOOTWEAR']/parent::*</value>
      <webElementGuid>9bf7722a-324e-4bc0-b0ac-5c0306dfc002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/collections/all-essentials')])[2]</value>
      <webElementGuid>84fcbdc9-8d0a-4f2f-b989-b49f996f2f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>654fec1e-a1ca-41ad-9f3f-57666a1c8b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/collections/all-essentials' and (text() = 'NON-FOOTWEAR ' or . = 'NON-FOOTWEAR ')]</value>
      <webElementGuid>48130860-2128-4003-8820-1d6dcb39864f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
