<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Availability_tag__checkbox</name>
   <tag></tag>
   <elementGuidId>41167443-4976-4d9d-9eb2-0e5a9e833527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CollectionFiltersSection']/form/div/div/ul/li/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.tag__checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>974274cd-4ca2-4141-a0e1-34774f8358c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tag__checkbox</value>
      <webElementGuid>99eac637-b39f-42a9-bc30-c1e8001628d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CollectionFiltersSection&quot;)/form[@class=&quot;filter-form collection-filter__scrollable aos-init aos-animate&quot;]/div[@class=&quot;collection-filter__group collection-filter__group--1&quot;]/div[@class=&quot;collection-filter__inner&quot;]/ul[@class=&quot;no-bullets tag-list&quot;]/li[@class=&quot;tag&quot;]/label[@class=&quot;tag__checkbox-wrapper text-label js-no-transition&quot;]/span[@class=&quot;tag__checkbox&quot;]</value>
      <webElementGuid>f8d229d6-cc74-4508-90f6-00ccddce1d9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollectionFiltersSection']/form/div/div/ul/li/label/span</value>
      <webElementGuid>a4b5bd28-31d0-4a93-be41-32230d7b4b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>521924b6-f904-46e3-b70a-d6783fc6e157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
