<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bigger Trucker Hat All Black</name>
   <tag></tag>
   <elementGuidId>370f0572-9920-45b3-a7cb-75ae0aba8113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CollectionAjaxContent']/div/div[2]/div/a/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.grid-product__link.quick-product__btn.js-screen-open-product-7659508564159.js-no-transition > div.grid-product__meta > div.grid-product__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee1a7421-0520-4520-9bf1-e8dabd9a08f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-product__title</value>
      <webElementGuid>6e040d1d-d2bb-44bd-8cd4-51000e755fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bigger Trucker Hat All Black</value>
      <webElementGuid>2a0d821b-257b-44ce-bea8-09c30514f230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CollectionAjaxContent&quot;)/div[@class=&quot;grid grid--uniform grid--scattered-large-4 grid--scattered-small-2 small--grid--flush&quot;]/div[@class=&quot;grid__item grid-product small--one-half medium-up--one-quarter aos-init aos-animate&quot;]/div[@class=&quot;grid-product__content&quot;]/a[@class=&quot;grid-product__link quick-product__btn js-screen-open-product-7659508564159 js-no-transition&quot;]/div[@class=&quot;grid-product__meta&quot;]/div[@class=&quot;grid-product__title&quot;]</value>
      <webElementGuid>d50c91ef-8519-4bcc-a8dd-07c63b82f731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollectionAjaxContent']/div/div[2]/div/a/div[2]/div</value>
      <webElementGuid>fa63d8d1-7d65-4af8-9c43-3ab1a28f4c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 108.000,00'])[2]/preceding::div[1]</value>
      <webElementGuid>5a84bcc4-6cc7-4f4e-a925-c32725e42e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bigger Trucker Hat All Black']/parent::*</value>
      <webElementGuid>092eef67-3b25-4256-a9a6-61893e50a001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div[2]/div</value>
      <webElementGuid>ef5e90d8-2d5c-41a1-a484-da2110d45350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bigger Trucker Hat All Black' or . = 'Bigger Trucker Hat All Black')]</value>
      <webElementGuid>1f1dc883-3f58-44f7-ae41-84fa6167ecfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
